# Generated by Django 4.2.7 on 2024-12-23 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_books_price_books_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='price',
        ),
        migrations.RemoveField(
            model_name='books',
            name='quantity',
        ),
    ]
